name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        uses: kunihiko-t/review-request-action@v0.1.3
        with:
          repo-token: ${{ secrets.TOKEN }}
          reviewers: "president"
  deploy:
    needs: [review]
    runs-on: ubuntu-latest
    steps:
      - name: say Yay
        run: |
          echo Yaj!!
        
